# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ce27983cf3420f77914cc3acb8d97f7cffb092b77fa38f4ae5803fc48febc721c3bcce49ca40263a8d9d68fa42fe3db2a890faf45f9bebb3d5a521e1761bae

test:
  secret_key_base: 71d74b980e1bc4bc2c032214c39ee966467a5b7b1704716c8266325453e8064503c55ed59abd6c99c056a96508e6c1c8aca8ee4ff22a3dc1f6a3917406cc1b9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
